fix: Add await to getUsers() call in login function
- Fixed TypeError: users.find is not a function
- getUsers() is async but was not being awaited
- Caused login to fail for all users

Fixes login authentication